In [1]:
#sort ,Search and Counting Function

In [2]:
import numpy as np

In [5]:
arr= np.array([4, 3, 4, 5, 6, 72, 3, 3, 455, 5, 6, 6])

In [6]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [7]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [8]:
np.searchsorted(arr, 34)

12

In [9]:
arr1 = np.array([0, 345, 454, 0, 0, 0, 0,0])

In [10]:
np.count_nonzero(arr1)

2

In [11]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [12]:
np.where(arr>6)

(array([5, 8], dtype=int64),)

In [14]:
np.extract(arr>3 , arr)

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])

In [15]:
#Numpy -Byte Swapping

In [16]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [17]:
arr.byteswap()

array([  67108864,   50331648,   67108864,   83886080,  100663296,
       1207959552,   50331648,   50331648, -956235776,   83886080,
        100663296,  100663296])

In [18]:
#Numpy -Copies Sviews

In [19]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [20]:
a = np.copy(arr)

In [24]:
b = arr.view()

In [ ]:
b = arr

In [22]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [23]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [25]:
b[0] = 67

In [26]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [27]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [28]:
#Numpy - Matrix Library

In [29]:
import numpy.matlib as nm

In [30]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [31]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [34]:
#Numpy -Linear Algebra

In [35]:
arr2 = np.random.randint([[2,3], [4,5]])

In [37]:
arr3 = np.random.randint([[5,3], [2,5]])

In [38]:
np.dot(arr2,arr3)

array([[0, 4],
       [2, 1]])

In [39]:
arr2@arr3

array([[0, 4],
       [2, 1]])