In [1]:
#numpy Array manipulation

In [2]:
import numpy as np

In [5]:
arr =  np.random.randint(1, 10, (3,4))

In [6]:
arr

array([[6, 7, 8, 8],
       [2, 6, 4, 4],
       [3, 5, 3, 4]])

In [7]:
arr.reshape(6,2)

array([[6, 7],
       [8, 8],
       [2, 6],
       [4, 4],
       [3, 5],
       [3, 4]])

In [8]:
arr.reshape(2,6)

array([[6, 7, 8, 8, 2, 6],
       [4, 4, 3, 5, 3, 4]])

In [9]:
arr.T

array([[6, 2, 3],
       [7, 6, 5],
       [8, 4, 3],
       [8, 4, 4]])

In [10]:
arr

array([[6, 7, 8, 8],
       [2, 6, 4, 4],
       [3, 5, 3, 4]])

In [11]:
arr.flatten()

array([6, 7, 8, 8, 2, 6, 4, 4, 3, 5, 3, 4])

In [12]:
arr1 = np.array([1,2,3,4])

In [13]:
arr1.ndim

1

In [14]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [15]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 4]])

In [16]:
arr

array([[6, 7, 8, 8],
       [2, 6, 4, 4],
       [3, 5, 3, 4]])

In [17]:
np.squeeze(arr)

array([[6, 7, 8, 8],
       [2, 6, 4, 4],
       [3, 5, 3, 4]])

In [19]:
data = np.array([[1] ,[2], [3]])

In [20]:
data

array([[1],
       [2],
       [3]])

In [21]:
np.squeeze(data)

array([1, 2, 3])

In [22]:
arr1

array([1, 2, 3, 4])

In [23]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [26]:
np.roll(arr1,2)

array([3, 4, 1, 2])

In [27]:
""" ye index wise gumata hain """

' ye index wise gumata hain '

In [29]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [30]:
#numpy  Binary operation

In [31]:
arr2 = np.random.randint(1, 10,(3,4)) 

In [32]:
arr3 = np.random.randint(1,10,(3,4))

In [33]:
arr2

array([[7, 7, 6, 4],
       [9, 6, 8, 4],
       [8, 1, 7, 6]])

In [34]:
arr3

array([[4, 2, 7, 7],
       [7, 1, 6, 4],
       [2, 1, 1, 7]])

In [36]:
arr2 + arr3

array([[11,  9, 13, 11],
       [16,  7, 14,  8],
       [10,  2,  8, 13]])

In [37]:
arr2*arr3

array([[28, 14, 42, 28],
       [63,  6, 48, 16],
       [16,  1,  7, 42]])

In [38]:
arr2/arr3

array([[1.75      , 3.5       , 0.85714286, 0.57142857],
       [1.28571429, 6.        , 1.33333333, 1.        ],
       [4.        , 1.        , 7.        , 0.85714286]])

In [39]:
arr2-arr3

array([[ 3,  5, -1, -3],
       [ 2,  5,  2,  0],
       [ 6,  0,  6, -1]])

In [40]:
arr2%arr3

array([[3, 1, 6, 4],
       [2, 0, 2, 0],
       [0, 0, 0, 6]])

In [42]:
arr2 ** arr3

array([[   2401,      49,  279936,   16384],
       [4782969,       6,  262144,     256],
       [     64,       1,       7,  279936]])

In [43]:
arr2 & arr3

array([[4, 2, 6, 4],
       [1, 0, 0, 4],
       [0, 1, 1, 6]])

In [44]:
arr2

array([[7, 7, 6, 4],
       [9, 6, 8, 4],
       [8, 1, 7, 6]])

In [45]:
arr3

array([[4, 2, 7, 7],
       [7, 1, 6, 4],
       [2, 1, 1, 7]])

In [46]:
~ arr3

array([[-5, -3, -8, -8],
       [-8, -2, -7, -5],
       [-3, -2, -2, -8]])

In [47]:
arr2 | arr3

array([[ 7,  7,  7,  7],
       [15,  7, 14,  4],
       [10,  1,  7,  7]])

In [48]:
arr2 >arr3

array([[ True,  True, False, False],
       [ True,  True,  True, False],
       [ True, False,  True, False]])

In [49]:
# numpy  String function

In [50]:
arr4 = np.array(["kavan", "kumar"])

In [51]:
arr4

array(['kavan', 'kumar'], dtype='<U5')

In [52]:
np.char.upper(arr4)

array(['KAVAN', 'KUMAR'], dtype='<U5')

In [53]:
np.char.title(arr4)

array(['Kavan', 'Kumar'], dtype='<U5')

In [54]:
np.char.capitalize(arr4)

array(['Kavan', 'Kumar'], dtype='<U5')

In [55]:
#numpy - Mathematical function

In [56]:
arr1

array([1, 2, 3, 4])

In [57]:
arr2

array([[7, 7, 6, 4],
       [9, 6, 8, 4],
       [8, 1, 7, 6]])

In [59]:
np.sin(arr2)

array([[ 0.6569866 ,  0.6569866 , -0.2794155 , -0.7568025 ],
       [ 0.41211849, -0.2794155 ,  0.98935825, -0.7568025 ],
       [ 0.98935825,  0.84147098,  0.6569866 , -0.2794155 ]])

In [60]:
np.cos(arr2)

array([[ 0.75390225,  0.75390225,  0.96017029, -0.65364362],
       [-0.91113026,  0.96017029, -0.14550003, -0.65364362],
       [-0.14550003,  0.54030231,  0.75390225,  0.96017029]])

In [61]:
np.tan(arr2)

array([[ 0.87144798,  0.87144798, -0.29100619,  1.15782128],
       [-0.45231566, -0.29100619, -6.79971146,  1.15782128],
       [-6.79971146,  1.55740772,  0.87144798, -0.29100619]])

In [62]:
np.tanh(arr2)

array([[0.99999834, 0.99999834, 0.99998771, 0.9993293 ],
       [0.99999997, 0.99998771, 0.99999977, 0.9993293 ],
       [0.99999977, 0.76159416, 0.99999834, 0.99998771]])

In [63]:
np.log10(arr2)

array([[0.84509804, 0.84509804, 0.77815125, 0.60205999],
       [0.95424251, 0.77815125, 0.90308999, 0.60205999],
       [0.90308999, 0.        , 0.84509804, 0.77815125]])

In [64]:
np.sqrt(arr2)

array([[2.64575131, 2.64575131, 2.44948974, 2.        ],
       [3.        , 2.44948974, 2.82842712, 2.        ],
       [2.82842712, 1.        , 2.64575131, 2.44948974]])

In [65]:
np.power(arr2,2)

array([[49, 49, 36, 16],
       [81, 36, 64, 16],
       [64,  1, 49, 36]], dtype=int32)

In [66]:
np.mean(arr2)

6.083333333333333

In [67]:
np.median(arr2)

6.5

In [68]:
np.std(arr2)

2.099933861392359

In [69]:
np.var(arr2)

4.409722222222222

In [70]:
np.max(arr2)

9